# Site settings
title: Daniel Morrison
email: dan@morrison.ph
description: "So that's where I put it."
baseurl: ""
url: "http://dan.morrison.ph"
twitter_username: dmorrison42
github_username:  dmorrison42

# Build settings
markdown: kramdown
permalink: pretty
